services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://server:v9023aSH@@db:5432/fortran
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: server
      POSTGRES_PASSWORD: v9023aSH@
      POSTGRES_DB: fortran
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
